//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lohovskayaProga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int AircraftID { get; set; }
        public int RouteID { get; set; }
        public decimal EconomyPrice { get; set; }
        public bool Confirmed { get; set; }
        public string FlightNumber { get; set; }

        public Nullable<double> BuisnessPrice {
            get
            {
                return Math.Floor(Convert.ToDouble(EconomyPrice) * 1.35);
            }
            set
            {
                BuisnessPrice = Math.Floor(Convert.ToDouble(EconomyPrice) * 1.35);
            }
        }
        public Nullable<double> FirstClassPrice {
            get
            {
                return Math.Floor(Convert.ToDouble(BuisnessPrice) * 1.3);
            }
            set
            {
                
            }
        }

        public virtual Aircraft Aircraft { get; set; }
        public virtual Route Route { get; set; }
    }
}
